"""Add environment tables

Revision ID: 103baff07c73
Revises: 9a103ff5378e
Create Date: 2022-04-09 13:06:45.781992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103baff07c73'
down_revision = '9a103ff5378e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('carbon_footprint', sa.Integer(), nullable=False),
    sa.Column('carbon_deviation', sa.Integer(), nullable=False),
    sa.Column('carbon_percentage_manufacturing', sa.Float(), nullable=True),
    sa.Column('carbon_percentage_transportation', sa.Float(), nullable=True),
    sa.Column('carbon_percentage_eol', sa.Float(), nullable=True),
    sa.Column('carbon_percentage_use', sa.Float(), nullable=True),
    sa.Column('weight_kg_assumption', sa.Float(), nullable=False),
    sa.Column('lifetime_year_assumption', sa.Integer(), nullable=False),
    sa.Column('screen_size_assumption', sa.Integer(), nullable=True),
    sa.Column('use_location_assumption', sa.String(), nullable=False),
    sa.Column('assembly_location_assumption', sa.String(), nullable=False),
    sa.Column('energy_demand_kwh_assumption', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('report_created', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment_manufacturing_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('environment_manufacturing_component')
    op.drop_table('environment')
    # ### end Alembic commands ###
