"""Add size, creation date and checksum to document table

Revision ID: 25ff747bf171
Revises: a68540e4117f
Create Date: 2022-01-04 16:33:03.098870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ff747bf171'
down_revision = 'a68540e4117f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('document', sa.Column('file_created_at', sa.Date(), nullable=True))
    op.add_column('document', sa.Column('checksum', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'checksum')
    op.drop_column('document', 'file_created_at')
    op.drop_column('document', 'size')
    # ### end Alembic commands ###
