"""Add product.id to attribute

Revision ID: 6630c067c639
Revises: 35ce34d4e586
Create Date: 2021-12-22 09:29:20.752566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6630c067c639'
down_revision = '35ce34d4e586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attribute', 'product', ['product_id'], ['id'])
    op.drop_constraint('product_attribute_id_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'attribute_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('attribute_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('product_attribute_id_fkey', 'product', 'attribute', ['attribute_id'], ['id'])
    op.drop_constraint(None, 'attribute', type_='foreignkey')
    op.drop_column('attribute', 'product_id')
    # ### end Alembic commands ###
