"""Add role to user table

Revision ID: 9a103ff5378e
Revises: 03e883463ff1
Create Date: 2022-01-23 16:58:53.094071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a103ff5378e'
down_revision = '03e883463ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.create_table('stats',
    sa.Column('index', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('response_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('remote_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exception', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('referrer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('browser', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mimetype', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('index', name='stats_pkey')
    )
    # ### end Alembic commands ###
